name:                hdbcperf
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/gbwey/hdbcperf#readme
license:             BSD3
author:              Author name here
maintainer:          gbwey9@gmail.com
copyright:           2018 gbwey
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - time
  - odbc == 0.2.0
  - HDBC-odbc == 2.5.0.2
  - split
  - HDBC == 2.4.0.3
  - text
  - bytestring
  - criterion
  - optparse-applicative
  - transformers
  - mtl
  - directory
  
executables:
  hdbcperf:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -threaded
